server:
  port: 8086
spring:
  jpa:
    database: h2
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
    platform: org.hibernate.dialect.H2Dialect
logging:
  level:
    org.hibernate.SQL: DEBUG
    #org.hibernate.type: TRACE